### ISSUE TITLE
Cannot fly with infinity chestplate

### ISSUE THREAD

**Issue by unix-supremacist** [Laith471/Avaritia-Fabric#5]
i assume related to fix for #3 i can't fly with the infinity chestplate in survival anymore, PAL also spams the log a ton with

```[17:12:34] [Server thread/WARN]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
java.lang.RuntimeException: stacktrace
	at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63) ~[playerabilitylib-1.8.0-4683a0cc11f08713.jar:?]
	at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[playerabilitylib-1.8.0-4683a0cc11f08713.jar:?]
	at net.minecraft.class_3222.handler$igg000$playerabilitylib$checkAbilityConsistency(class_3222.java:15924) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_7355(class_3222.java:1323) ~[client-intermediary.jar:?]
	at net.laith.avaritia.common.handler.InfinityHandler$Server.onServerTick(InfinityHandler.java:25) ~[avaritia-0.4.jar:?]
	at net.laith.avaritia.common.handler.InfinityHandler$Server.onStartTick(InfinityHandler.java:39) ~[avaritia-0.4.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-2797ff451c2ba64e.jar:?]
	at net.minecraft.server.MinecraftServer.handler$efi000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:10357) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$boh000$carpet$modifiedRunLoop(MinecraftServer.java:15442) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by Laith471** [comment]
Very weird I've tried it before and it works fine I'll give it a try in the meantime please try it without any mod and see if the crash still exists
Thanks

**Comment by unix-supremacist** [comment]
alone avaritia fabric flying works, as soon as you add playerabilitylib which most mods use it doesn't

**Comment by Laith471** [comment]
Then I will try to make it compatible with PAL I will update you on it if anything happen
Thanks for reporting

**Comment by Leclowndu93150** [comment]
poggers
